name: Bug Report (CLI Tool)
description: File a bug report.
title: "[Bug][CLI]: "
labels: ["bug", "cli"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug!
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the behavior you are seeing and the expected behavior along with steps to reproduce it.
      placeholder: When running a type check with `pyrefly ...`, I expect to see ABC, but get XYZ instead
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Codebase
      description: If possible, please provide a reproducible sample of the code you are experiencing the issue in the [Pyrefly Sandbox](https://pyrefly.org/try/) if possible. In complicated cases, a github commit with a list of your third-party dependencies works.
      placeholder: Pyrefly Sandbox link or https://github.com/<owner>/<repo>/path/to/file.py on lines 123-456 at commit hash <123456>
    validations:
      required: false
  - type: textarea
    id: other-attempts
    attributes:
      label: Other Attempts
      description: Have you tried anything else? Are you running Pyrefly in your IDE and seeing similar or different behavior?
      placeholder: ...
    validations:
      required: false
